spring:
  application:
    name: veterinaria

  # --- Base de datos real: PostgreSQL local, administrada con pgAdmin 4 ---
  datasource:
    url: jdbc:postgresql://localhost:5432/VeterinariaS
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD:1234}

  # --- JPA / Hibernate ---
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
